config/routes.rb
Rails.application.routes.draw do
  resources :job_govs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'job_govs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_gov.rb
class JobGov < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_govs_controller.rb
class JobGovsController < ApplicationController
  before_action :set_job_gov, only: [:show, :edit, :update, :destroy]

  # GET /job_govs
  # GET /job_govs.json
  def index
    @job_govs = JobGov.all
  end

  # GET /job_govs/1
  # GET /job_govs/1.json
  def show
  end

  # GET /job_govs/new
  def new
    @job_gov = JobGov.new
  end

  # GET /job_govs/1/edit
  def edit
  end

  # POST /job_govs
  # POST /job_govs.json
  def create
    @job_gov = JobGov.new(job_gov_params)

    respond_to do |format|
      if @job_gov.save
        format.html { redirect_to @job_gov, notice: 'Job gov was successfully created.' }
        format.json { render :show, status: :created, location: @job_gov }
      else
        format.html { render :new }
        format.json { render json: @job_gov.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_govs/1
  # PATCH/PUT /job_govs/1.json
  def update
    respond_to do |format|
      if @job_gov.update(job_gov_params)
        format.html { redirect_to @job_gov, notice: 'Job gov was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_gov }
      else
        format.html { render :edit }
        format.json { render json: @job_gov.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_govs/1
  # DELETE /job_govs/1.json
  def destroy
    @job_gov.destroy
    respond_to do |format|
      format.html { redirect_to job_govs_url, notice: 'Job gov was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_gov
      @job_gov = JobGov.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_gov_params
      params.require(:job_gov).permit(:post, :vacancy, :qualification, :fitness, :age, :place, :fee, :date, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_govs_helper.rb
module JobGovsHelper
end

app/views/job_govs/_form.html.erb
<%= form_with(model: job_gov, local: true) do |form| %>
  <% if job_gov.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_gov.errors.count, "error") %> prohibited this job_gov from being saved:</h2>

      <ul>
      <% job_gov.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_field :post %>
  </div>

  <div class="field">
    <%= form.label :vacancy %>
    <%= form.text_field :vacancy %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification %>
  </div>

  <div class="field">
    <%= form.label :fitness %>
    <%= form.text_field :fitness %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.text_field :fee %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_govs/edit.html.erb
<h1>Editing Job Gov</h1>

<%= render 'form', job_gov: @job_gov %>

<%= link_to 'Show', @job_gov %> |
<%= link_to 'Back', job_govs_path %>

app/views/job_govs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>GovJob</h1>

<table>
  <thead>
    <tr>
      <th>Post Name</th>
      <th>Vacancy</th>
      <th>Qualification</th>
      <th>Physical Fitness</th>
      <th>Age Limit</th>
      <th>Job Place</th>
      <th>Applicable Fees</th>
      <th>Last Date</th>
      <th>Online Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_govs.each do |job_gov| %>
      <tr>
        <td><%= job_gov.post %></td>
        <td><%= job_gov.vacancy %></td>
        <td><%= job_gov.qualification %></td>
        <td><%= job_gov.fitness %></td>
        <td><%= job_gov.age %></td>
        <td><%= job_gov.place %></td>
        <td><%= job_gov.fee %></td>
        <td><%= job_gov.date %></td>
        <td><%= job_gov.link %></td>
        <td><%= link_to 'Show', job_gov %></td>
        <td><%= link_to 'Edit', edit_job_gov_path(job_gov) %></td>
        <td><%= link_to 'Destroy', job_gov, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New GovJob', new_job_gov_path %>

app/views/job_govs/new.html.erb
<h1>New Job Gov</h1>

<%= render 'form', job_gov: @job_gov %>

<%= link_to 'Back', job_govs_path %>

app/views/job_govs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @job_gov.post %>
</p>

<p>
  <strong>Vacancy:</strong>
  <%= @job_gov.vacancy %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @job_gov.qualification %>
</p>

<p>
  <strong>Fitness:</strong>
  <%= @job_gov.fitness %>
</p>

<p>
  <strong>Age:</strong>
  <%= @job_gov.age %>
</p>

<p>
  <strong>Place:</strong>
  <%= @job_gov.place %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @job_gov.fee %>
</p>

<p>
  <strong>Date:</strong>
  <%= @job_gov.date %>
</p>

<p>
  <strong>Link:</strong>
  <%= @job_gov.link %>
</p>

<%= link_to 'Edit', edit_job_gov_path(@job_gov) %> |
<%= link_to 'Back', job_govs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>